# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Run workflow only when pushed to main branch.
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # My Deployment commands.
      - name: Create directory if not exits into /var/www/tote
        run: mkdir -p /var/www/tote

      - name: Show where is it.
        run: pwd

      - name: Add nvm
        run: |
          export NVM_DIR="/home/rezero/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
          [[ -r $NVM_DIR/bash_completion ]] && \. $NVM_DIR/bash_completion
          echo "$NVM_DIR"
          node -v
          npm -v

      - name: Install npm packages.
        run: |
          echo "$NVM_DIR"
          node -v
          npm -v
          npm install

      - name: Build vue.
        run: npm run build

      - name: Copy files into release directory
        run: rsync -av ./dist/ /var/www/tote --exclude .git/

      - name: Change owner of directory to www-data
        run: chown -R www-data:www-data /var/www/tote
