

name: CI


on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Create directory if not exits into /var/www/tote
        run: mkdir -p /var/www/tote

      - name: Show where is it.
        run: pwd

      - name: Copy files into release directory
        run: rsync -av ./dist/ /var/www/tote --exclude .git/

      - name: Change owner of directory to www-data
        run: chown -R www-data:www-data /var/www/tote
